version: '3.12'

services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data_two


  web:
    build:
      context: .
      dockerfile: Dockerfile
    # image: pette:0.8
    # command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db


volumes:
  db_data:
