# Generated by Django 5.0.3 on 2024-04-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_place_dog_size_alter_place_extra_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='Number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='Postal_Code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
