# Generated by Django 5.0.3 on 2024-04-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dogs_user_dogs_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dogs',
            new_name='Dog',
        ),
    ]
